# Generated by Django 5.0.6 on 2024-05-13 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=128, null=True, upload_to='user', verbose_name='缩略图')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户头像',
                'verbose_name_plural': '用户头像',
                'db_table': 'user_image',
            },
        ),
    ]
